- name: Master provision
  hosts: master

  tasks:
  - name: Set alias ll
    replace:
      path: /home/vagrant/.bashrc
      regexp: "^#alias ll='ls -l'$"
      replace: "alias ll='ls -la'"

  - name: Set colors
    replace:
      path: /home/vagrant/.bashrc
      regexp: "^#force_color_prompt=yes$"
      replace: "force_color_prompt=yes"

  - name: Install packages
    apt:
      pkg:
      - apache2
      - php
      - php-fpm
      - libapache2-mod-php
      state: present

  - name: Add listen port 81
    lineinfile:
      path: /etc/apache2/ports.conf
      line: Listen 81

  - name: Add section port 81 in the conf file
    blockinfile:
      path: /etc/apache2/sites-available/000-default.conf
      state: present
      block: |
        <VirtualHost *:81>
        DirectoryIndex index.php	
        </VirtualHost>

  - name: Download index.php
    get_url:
      url: https://raw.githubusercontent.com/maxmax03/devops-hometasks/main/02-lxc/index.php
      dest: /var/www/html/index.php
      
  - name: Download index.html
    get_url:
      url: https://raw.githubusercontent.com/maxmax03/devops-hometasks/main/02-lxc/index.html
      dest: /var/www/html/index.html
    notify: Restart packages

  handlers:
  - name: Restart packages
    service:
      name: apache2
      state: restarted