FROM golang:1.16 as app
RUN mkdir /wcg; \
    cd /wcg; \
    git clone https://github.com/Fenikks/word-cloud-generator.git .; \
    make

FROM alpine:latest
RUN apk add gcompat 
COPY --from=app /wcg/artifacts/linux/word-cloud-generator .
CMD /word-cloud-generator