version: '3'
services:
  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    ports:
      - 80:8080
    networks:
      - work
    container_name: jenkins
  nexus:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    ports:
      - 81:8081
    networks:
      - work
    container_name: nexus
networks:
  work: 
