Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder ".", "/vagrant"
   
    config.vm.define "nexus.vm" do |slave|
      slave.vm.network "private_network", ip: "192.168.33.12"
      slave.vm.network "forwarded_port", guest: 82, host: 8081
      slave.vm.hostname = "nexus.vm" 
      slave.vm.provider "virtualbox" do |vb|
         vb.memory = 4096
         vb.cpus   = 2     
       end
  
    end

     config.vm.define "staging.vm" do |slave|
       slave.vm.network "private_network", ip: "192.168.33.11"
       slave.vm.network "forwarded_port", guest: 81, host: 8082      
       slave.vm.hostname = "staging.vm"
        slave.vm.provider "virtualbox" do |vb|
          vb.memory = 512
          vb.cpus   = 1     
       end
  
     end   
  
       config.vm.define "production.vm" do |slave|
       slave.vm.network "private_network", ip: "192.168.33.13"
       slave.vm.network "forwarded_port", guest: 83, host: 8083      
       slave.vm.hostname = "production.vm"
         slave.vm.provider "virtualbox" do |vb|
           vb.memory = 512
           vb.cpus   = 1     
         end
        end 


       config.vm.define "jenkins.vm" do |master|
       master.vm.network "private_network", ip: "192.168.33.10"
       master.vm.network "forwarded_port", guest: 80, host: 8080      
       master.vm.hostname = "jenkins.vm"
          master.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus   = 1     
          end

         
       master.vm.provision :file, source: '.vagrant/machines/nexus.vm/virtualbox/private_key', destination: '/home/vagrant/private_key_nexus'
       master.vm.provision :file, source: '.vagrant/machines/staging.vm/virtualbox/private_key', destination: '/home/vagrant/private_key_staging'
       master.vm.provision :file, source: '.vagrant/machines/production.vm/virtualbox/private_key', destination: '/home/vagrant/private_key_production'

       master.vm.provision "shell", inline: <<-shell
         sudo chmod =600 /home/vagrant/private_key_nexus
         sudo chmod =600 /home/vagrant/private_key_staging
         sudo chmod =600 /home/vagrant/private_key_production
       shell
     
     
       master.vm.provision "ansible_local" do |ansible|
       ansible.galaxy_role_file = "requirements.yaml"
       ansible.playbook = "playbook.yaml"
       ansible.limit = "all"
       ansible.become = true
       ansible.inventory_path = "./hosts"       
        end
      end
end 