- name: Master provision
  hosts: master.puppet

  tasks:
  
  - rpm_key:
      state: present
      key: https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406
  
  - name: rpm
    yum:
      name: https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm  
        
  - name: Install package puppetserver & git
    yum:
      name: 
       - puppetserver
       - git
      state: present
 
  - name: Add conf .bashrc export PATH
    lineinfile: 
      path: /root/.bashrc
      line: export PATH="/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin:$PATH"

  - name: Add [agent] puppet.conf
    blockinfile: 
      path: /etc/puppetlabs/puppet/puppet.conf 
      block: |
        autosign = true

        [agent]
        environment = minecraft
        server = master.puppet
        runinterval = 1m

  - name: Copy a new puppet sysconfig - fix memmory usage
    copy:
      src: /vagrant/puppetserver
      dest: /etc/sysconfig/puppetserver

  - name: Add masterhost
    lineinfile: 
      path: /etc/hosts
      line: 192.168.50.1 master.puppet
  
  - name: Start puppet
    service:
      name: puppet
      state: started
      enabled: true

  - name: Start puppetserver
    service:
      name: puppetserver
      state: started
      enabled: true
    ignore_errors: true

  - name: Add ports to firewall
    firewalld:
      port: "8140/tcp"
      state: enabled
      immediate: true
      permanent: true

  - name: Install r10k
    gem:
      name: r10k
      executable: /opt/puppetlabs/puppet/bin/gem
      bindir: /opt/puppetlabs/puppet/bin/
      state: present

  - name: Create directory r10k
    file: 
      path: /etc/puppetlabs/r10k
      state: directory
      mode: '0775'

  - name: Conf r10k
    copy:
      dest: /etc/puppetlabs/r10k/r10k.yaml
      content: | 
        :cachedir: '/var/cache/r10k'
        :sources:
          :my-org:
            remote: 'https://github.com/maxmax03/master-puppet.git'
            basedir: '/etc/puppetlabs/code/environments'

  - name: Create & ensure a cronjob
    cron:
      name: "r10k git deploy"
      minute: "*/1"
      job: "/opt/puppetlabs/puppet/bin/r10k deploy environment -p > /tmp/r10k.log 2>&1"



- name: Slave1 provision
  hosts: slave1.puppet   
      
  tasks:
  - rpm_key:
      state: present
      key: https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406

  - name: rpm
    yum:
      name: https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm 

  - name: Install agent
    yum:
      name: puppet-agent    
      state: present

  - name: Add [agent] puppet.conf
    blockinfile: 
      path: /etc/puppetlabs/puppet/puppet.conf 
      block: |
        [agent]
        server = master.puppet
        runinterval = 1m

  - name: Add masterhost
    lineinfile: 
      path: /etc/hosts
      line: 192.168.50.1 master.puppet

  - name: Start puppet-agent
    service:
      name: puppet
      state: started
      enabled: true

  - name: Stop and disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false
    

    
- name: Slave2 provision
  hosts: slave2.puppet
  
  tasks:
  - rpm_key:
      state: present
      key: https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406

  - name: rpm
    yum:
      name: https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm 

  - name: Install agent
    yum:
      name: puppet-agent    
      state: present

  - name: Add [agent] puppet.conf
    blockinfile: 
      path: /etc/puppetlabs/puppet/puppet.conf 
      block: |
        [agent]
        server = master.puppet
        runinterval = 1m

  - name: Add masterhost
    lineinfile: 
      path: /etc/hosts
      line: 192.168.50.1 master.puppet

  - name: Start puppet-agent
    service:
      name: puppet
      state: started
      enabled: true

  - name: Stop and disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false



- name: Minecraft provision
  hosts: mineserver.puppet
  
  tasks:
  - rpm_key:
      state: present
      key: https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406

  - name: rpm
    yum:
      name: https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm 

  - name: Install agent
    yum:
      name: puppet-agent    
      state: present

  - name: Add [agent] puppet.conf
    blockinfile: 
      path: /etc/puppetlabs/puppet/puppet.conf 
      block: |
        [agent]
        server = master.puppet
        runinterval = 1m

  - name: Add masterhost
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.50.1 master.puppet

  - name: Start puppet-agent
    service:
      name: puppet
      state: started
      enabled: true

  - name: Stop and disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false