Vagrant.configure("2") do |config|
  config.vm.box = "maxsh-CentOS"
  config.vm.hostname = "centos8"
  config.vm.define "centos"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos"
    vb.memory = "1024"
    vb.cpus = 1
  end

  # config.vm.synced_folder ".", "/home/vagrant"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.provision "shell", inline: <<-SHELL
    yum update
    yum install -y httpd php mysql-server mc
    mkdir -p /var/www/localhost
    mkdir -p /var/www/localhost2
    curl https://raw.githubusercontent.com/Fenikks/devops-files/master/02-tools/files/index.html -o /var/www/localhost/index.html
    curl https://raw.githubusercontent.com/Fenikks/devops-files/master/02-tools/files/index.php -o /var/www/localhost2/index.php
    
    cat << EOF >> /etc/httpd/conf/httpd.conf
    Listen 81

    <VirtualHost *:80>
    DocumentRoot /var/www/localhost
    DirectoryIndex index.html
    </VirtualHost>

    <VirtualHost *:81>
    DocumentRoot /var/www/localhost2
    DirectoryIndex index.php  
    </VirtualHost>
EOF
    
    firewall-cmd --set-default-zone=trusted
    systemctl enable httpd.service
    systemctl restart mysqld.service
    service httpd restart
    service php-fpm restart
  SHELL
 
end