Vagrant.configure("2") do |config|
  config.vm.box = "generic-centos8"
  config.vm.hostname = "generic-centos8"
  config.vm.define "centos"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "generic-centos8"
    vb.memory = "1024"
    vb.cpus = 1
  end

  

  # config.vm.network "forwarded_port", guest: 3306, host: 3306

  config.vm.provision "shell", inline: <<-SHELL
    yum update
    yum install -y httpd
    yum install -y php 
    yum install -y mysql-server
    systemctl restart mysqld.service
    service httpd restart
    service php-fpm restart
  SHELL
 
end