version: '3'

services:
  nexus:
    build:
      context: .
      dockerfile: Dockerfile.Nexus
    image: nexus
    container_name: nexus
    network_mode: host


  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.Jenkins
    image: jenkins
    container_name: jenkins
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ws:/var/lib/jenkins/workspace/
    network_mode: host

volumes:
  ws: