name: GitHub lab CI

on: 
   workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
     - uses: actions/checkout@v3
     - name: Docker image
       run: docker build . --file /09-docker/Dockerfile.multi --tag my-image-name:wcg
