name: GitHub lab CI

on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
      - name: Docker image
        run: |
          docker build . --file Dockerfile.multi --tag my-image-name:wcg
          echo github.actor : ${{ github.actor }}
          echo github.repository : ${{ github.repository }}
         
      - name: Login GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
                 
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/${{ github.repository }}
          tag-custom: latest
          tag-semver: |
            {{raw}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
