name: GitHub lab CI

on: 
  push:
    branches: ['main']
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Ckeckout repository
        uses: actions/checkout@v3
        
      - name: Build image
        run: |
          GITHUB=$(echo $GITHUB_REPOSITORY_OWNER)
          docker build --tag wcg:latest --tag ghcr.io/$GITHUB/wcg:latest --tag ghcr.io/$GITHUB/wcg:${{ github.sha }} --file Dockerfile.multi .
          echo github.actor : ${{ github.actor }}
          echo ${{ GITHUB_REPOSITORY_OWNER }}
          
      - name: Push image
        run: |
          OWNER=$(echo $GITHUB_REPOSITORY_OWNER)
          echo ${{ secrets.ACTION_TOKEN }} | docker login ghcr.io -u $OWNER --password-stdin
          docker push ghcr.io/$OWNER/wcg:latest
          docker push ghcr.io/$OWNER/wcg:${{ github.sha }}
          
