name: GitHub lab CI

on: 
  push:
    branches: ['main']
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Ckeckout repository
        uses: actions/checkout@v3
        
      - name: Build image
        run: |
          GITHUB=$(echo $github.repository_owner)
          docker build -t wcg:latest -t ghcr.io/$GITHUB/wcg:latest -t ghcr.io/$GITHUB/wcg:${{ github.sha }} -f ./Dockerfile.multi .
          echo github.actor : ${{ github.actor }}
          echo ${{ github.repository_owner }}
          
      - name: Push image
        run: |
          GITHUB=$(echo $github.repository_owner)
          echo ${{ secrets.ACTION_TOKEN }} | docker login ghcr.io -u $GITHUB --password-stdin
          docker push ghcr.io/$GITHUB/wcg:latest
          docker push ghcr.io/$GITHUB/wcg:${{ github.sha }}
          
