name: GitHub lab CI

on: 
  push:
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
     - uses: actions/checkout@v3
     - name: Docker image
       run: |
         docker build . --file Dockerfile.multi --tag my-image-name:wcg
         echo github.actor : ${{ github.actor }}
         echo github.repository : ${{ github.repository }}
         
     - name: Login GitHub
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ secrets.USERNAME_TOKEN }}
         password: ${{ secrets.ACTION_TOKEN }}
        
     - name: Docker push
       run: |
         docker push ghcr.io/${{ github.repository }}:latest
