name: GitHub lab CI

on: 
  push:
    branches: ['main']
    tags:
      - v*
      
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build . --file Dockerfile.multi --tag my-image-name:wcg --label "runnumber=${GITHUB_RUN_ID}"
          echo github.actor : ${{ github.actor }}
          echo github.repository : ${{ github.repository }}
          
      - name: Log in to registry
        run: echo "${{ secrets.ACTION_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}

