name: GitHub lab CI

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  OWNER: '${{ github.repository_owner }}' 
  
jobs:
  build:
    runs-on: ubuntu-20.04
    # defaults:
    #   run:  
    #     working-directory: 11-github-actions
    # permissions:
    #   contents: read
    #   packages: write

    steps:
      - name: Ckeckout repository
        uses: actions/checkout@v3
        with:
          repository: maxmax03/devops-hometasks

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}     
      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}       
      - name: Push Docker image
        run: |
          docker build -t ghcr.io/${{ env.OWNER_LC }}/wcg:${{ github.sha }} -t  ghcr.io/${{ env.OWNER_LC }}/wcg:latest --file ./11-github-actions/Dockerfile.multi .
          docker push ghcr.io/${OWNER_LC}/wcg:${{ github.sha }}
          docker push ghcr.io/${OWNER_LC}/wcg:latest
