name: GitHub lab CI

on: 
  push:
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ckeckout repository
        uses: actions/checkout@v3
        with:
          repository: maxmax03/devops-hometasks
        
      - name: Build image
        id: build
        run: |
          OWNER=$(echo GITHUB_REPOSITORY_OWNER $ | tr '[:upper:]' '[:lower:]')
          docker build -t wcg:latest -t ghcr.io/$OWNER/wcg:latest -t ghcr.io/$OWNER/wcg:${{ github.sha }} --file ./Dockerfile.multi
          
      - name: Push image
        run: |
          OWNER=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          echo ${{ secrets.ACTION_TOKEN }} | docker login ghcr.io -u $OWNER --password-stdin
          docker push ghcr.io/$OWNER/wcg:latest
          docker push ghcr.io/$OWNER/wcg:${{ github.sha }}
          
