name: GitHub lab CI

on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
      - name: Docker image
        run: |
          docker build . --file Dockerfile.multi --tag my-image-name:wcg
          echo github.actor : ${{ github.actor }}
          echo github.repository : ${{ github.repository }}
         
      - name: Login GitHub
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
             
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
